### ISSUE TITLE
413 Request Entity Too Large nginx/1.25.1 (File stash)

### ISSUE THREAD

**Issue by SirdLay** [TheodoreKrypton/tgfs#20]
File size: 700MB 
File Typ: Mkv

I tried to upload the same file using a telegram bot where I received error as:  ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

Files upto 100MB is uploaded successfully

**Comment by TheodoreKrypton** [comment]
Hi, thanks for using it. I have tried uploading a file of around 800MB with both CLI and WebDAV, and it worked without issue. Can you please share the WebDAV client you were using? Also, you can test with the following command and let me know if it works
`tgfs cmd cp [local file path] /`
