### ISSUE TITLE
 errorMessage: 'INPUT_FILTER_INVALID'

### ISSUE THREAD

**Issue by klyamkovya** [TheodoreKrypton/tgfs#23]
Компилировал на Win11x64 через консоль nmp 10.5.0. Файл конфигурации заново создавался при запуске, telegramm запросил разрешения на подключение, затем выдал 
d:\tgfs\node_modules\.bin>tgfs -w
[2024-03-11T10:38:43.390] [INFO] - [Running gramJS version 2.18.37]
[2024-03-11T10:38:43.399] [INFO] - [Connecting to 149.154.167.50:80/TCPFull...]
[2024-03-11T10:38:43.497] [INFO] - [Connection to 149.154.167.50:80/TCPFull complete!]
[2024-03-11T10:38:43.499] [INFO] - [Using LAYER 160 for initial connect]
[2024-03-11T10:38:43.716] [INFO] - [Running gramJS version 2.18.37]
[2024-03-11T10:38:43.717] [INFO] - [Connecting to 149.154.167.50:80/TCPFull...]
[2024-03-11T10:38:43.812] [INFO] - [Connection to 149.154.167.50:80/TCPFull complete!]
[2024-03-11T10:38:43.812] [INFO] - [Using LAYER 160 for initial connect]
d:\tgfs\node_modules\telegram\errors\index.js:28
    return new RPCBaseErrors_1.RPCError(rpcError.errorMessage, request, rpcError.errorCode);
           ^

RPCError: 400: INPUT_FILTER_INVALID (caused by messages.SearchGlobal)
    at RPCMessageToError (d:\tgfs\node_modules\telegram\errors\index.js:28:12)
    at MTProtoSender._handleRPCResult (d:\tgfs\node_modules\telegram\network\MTProtoSender.js:534:58)
    at MTProtoSender._processMessage (d:\tgfs\node_modules\telegram\network\MTProtoSender.js:464:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MTProtoSender._recvLoop (d:\tgfs\node_modules\telegram\network\MTProtoSender.js:415:17) {
  code: 400,
  errorMessage: 'INPUT_FILTER_INVALID'
}

Node.js v20.11.1
Что можно сделать?

**Comment by TheodoreKrypton** [comment]
Hello. Is there a pinned "metadata.json" file in your file channel?

**Comment by klyamkovya** [comment]
Hello. To be honest, I don't know how to do this( 

But if you tell me, I can

**Comment by klyamkovya** [comment]
Here are all my actions. The config was created step by step, based on requests
D:\Users\KlyamkovYA>D:\tgfs\node_modules\.bin\tgfs.cmd -w
? The config file is malformed or not found. Create a config file now? Yes
? Where do you want to save this config file D:\Users\KlyamkovYA\config.yaml
? Visit https://my.telegram.org/apps, create an app and paste the app_id, app_token here
App api_id xxxxxxx
? App api_hash xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
? Where do you want to save the account session D:\Users\KlyamkovYA\tgfs
? Where do you want to save the bot session D:\Users\KlyamkovYA\tgfs
? Create a bot from https://t.me/botfather and paste the bot token here
Bot token xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
? Create a PRIVATE channel and paste the channel id here
Channel to store the files https://t.me/xxxxxxxxxxxxxxxxx
[2024-03-11T14:52:56.244] [INFO] - [Running gramJS version 2.18.37]
[2024-03-11T14:52:56.249] [INFO] - [Connecting to 149.154.167.91:80/TCPFull...]
[2024-03-11T14:52:58.023] [INFO] - [Connection to 149.154.167.91:80/TCPFull complete!]
[2024-03-11T14:52:58.024] [INFO] - [Using LAYER 160 for initial connect]
? phone number? +79129059078
[2024-03-11T14:53:21.839] [INFO] - [Phone migrated to 2]
[2024-03-11T14:53:21.951] [INFO] - [Reconnecting to new data center 2]
[2024-03-11T14:53:22.062] [WARN] - [Disconnecting...]
[2024-03-11T14:53:22.063] [INFO] - [Disconnecting from 149.154.167.91:80/TCPFull...]
[2024-03-11T14:53:22.063] [INFO] - [Connecting to 149.154.167.50:80/TCPFull...]
[2024-03-11T14:53:24.031] [INFO] - [Connection to 149.154.167.50:80/TCPFull complete!]
[2024-03-11T14:53:24.031] [INFO] - [Using LAYER 160 for initial connect]
? one-time code? 15002
[2024-03-11T14:53:43.618] [INFO] - [Signed in successfully as Юрий Клямков]
[2024-03-11T14:53:43.620] [INFO] - [Running gramJS version 2.18.37]
[2024-03-11T14:53:43.621] [INFO] - [Connecting to 149.154.167.50:80/TCPFull...]
[2024-03-11T14:53:43.721] [INFO] - [Connection to 149.154.167.50:80/TCPFull complete!]
[2024-03-11T14:53:43.721] [INFO] - [Using LAYER 160 for initial connect]
D:\tgfs\node_modules\telegram\errors\index.js:28
    return new RPCBaseErrors_1.RPCError(rpcError.errorMessage, request, rpcError.errorCode);
           ^
RPCError: 400: INPUT_FILTER_INVALID (caused by messages.SearchGlobal)
    at RPCMessageToError (D:\tgfs\node_modules\telegram\errors\index.js:28:12)
    at MTProtoSender._handleRPCResult (D:\tgfs\node_modules\telegram\network\MTProtoSender.js:534:58)
    at MTProtoSender._processMessage (D:\tgfs\node_modules\telegram\network\MTProtoSender.js:464:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MTProtoSender._recvLoop (D:\tgfs\node_modules\telegram\network\MTProtoSender.js:415:17) {
  code: 400,
  errorMessage: 'INPUT_FILTER_INVALID'
}
Node.js v20.11.1
There are no files on the channel(. Or I don’t know where to look

**Comment by klyamkovya** [comment]
After editing the same error occurred. I deleted the config file, ran \tgfs\node_modules\.bin\tgfs.cmd -w again. I entered all the details of the bot and channel, without https://t.me/, and got the same error. Maybe the problem is that I'm running the script from my home network due to NAT?

**Comment by TheodoreKrypton** [comment]
Can you confirm again that the channel id you put in the config contains only numbers?

**Comment by klyamkovya** [comment]
ID не только из цифр состоит, там и буквы есть и спецсимволы
Вот так примерно (изменено) https://t.me/+ghURDKn8KlGfRTD9
In the config I only use this part +ghURDKn8KlGfRTD9

**Comment by klyamkovya** [comment]
I installed ubuntu on a virtual machine, compiled with npm 10.5.0 and got the same error.
![error](https://github.com/TheodoreKrypton/tgfs/assets/59743232/bdf19d2b-d935-437f-9234-52d93f2521bc)
I'm desperate

**Comment by TheodoreKrypton** [comment]
> ID consists not only of numbers, there are also letters and special characters
> Something like this (modified) https://t.me/+ghURDKn8KlGfRTD9
> In the config I only use this part +ghURDKn8KlGfRTD9

I think this is the reason. The id should be a pure number. And please refer to this [part](https://github.com/TheodoreKrypton/tgfs?tab=readme-ov-file#set-up-the-channel-to-store-files) to obtain a legit id. Right click on any message and copy the url. The channel id is in the url.

**Comment by klyamkovya** [comment]
Oh yes, I found it! Should the value /1 at the end of the channel number also be added? /xxxxxxxxxx/1 or xxxxxxxxxx ?

**Comment by klyamkovya** [comment]
Yes, it worked! Thank you for your patience)

**Comment by TheodoreKrypton** [comment]
You are welcome. The password can be set directly in the config file. Any webdav client should work.

**Comment by klyamkovya** [comment]
I tried to set a password in this section
tgfs:
  users:
    user: test
      password: test
But then when you run the tgfs -w script, it is reported
? The config file is malformed or not found. Create a config file now? (Y/n)
and a new config.yaml is created

**Comment by Andrew666** [comment]
> I tried to set a password in this section tgfs: users: user: test password: test But then when you run the tgfs -w script, it is reported ? The config file is malformed or not found. Create a config file now? (Y/n) and a new config.yaml is created A script running on Ubuntu when trying to connect to a WebDAV server reports [2024-03-16T11:00:18.239] [INFO] GET / [2024-03-16T11:00:18.240] [INFO] GET 405 Get method not working?

I have the same problem.

**Comment by klyamkovya** [comment]
And it can only be launched via perl tgfs -w
Is this normal?

**Comment by TheodoreKrypton** [comment]
> And it can only be launched via **_perl tgfs -w_** Is this normal?

I am not sure with that. I haven't used perl before but tgfs is installed as a binary command, so perhaps perl can execute it somehow.

> I tried to set a password in this section tgfs: users: user: test password: test But then when you run the tgfs -w script, it is reported ? The config file is malformed or not found. Create a config file now? (Y/n) and a new config.yaml is created A script running on Ubuntu when trying to connect to a WebDAV server reports [2024-03-16T11:00:18.239] [INFO] GET / [2024-03-16T11:00:18.240] [INFO] GET 405 Get method not working?

The user part of the config should look like
```
...
tgfs:
  users:
    test:
      password: test
...
```
in your case

**Comment by klyamkovya** [comment]
Yes, I tried to write user: test password: test in the config.yaml file, but after that the command when launched displays _The config file is malformed or not found. Create a config file now? (Y/n)_ seems like config.yaml is missing. If you refuse, there is no launch, if you create a new one, there is no user and password.

**Comment by TheodoreKrypton** [comment]
> Yes, I tried to write user: test password: test in the config.yaml file, but after that the command when launched displays _The config file is malformed or not found. Create a config file now? (Y/n)_ seems like config.yaml is missing. If you refuse, there is no launch, if you create a new one, there is no user and password.

No. Please take a care look at it. It's not
```yaml
user: test
password: test
```
instead, it should be
```yaml
users:
    test:  (this is the user name)
        password: test
```

**Comment by klyamkovya** [comment]
Yes, it works. But after logging into the WebDAV page - HTTP ERROR 405

**Comment by Andrew666** [comment]
> > And it can only be launched via **_perl tgfs -w_** Is this normal?
> 
> I am not sure with that. I haven't used perl before but tgfs is installed as a binary command, so perhaps perl can execute it somehow.
> 
> > I tried to set a password in this section tgfs: users: user: test password: test But then when you run the tgfs -w script, it is reported ? The config file is malformed or not found. Create a config file now? (Y/n) and a new config.yaml is created A script running on Ubuntu when trying to connect to a WebDAV server reports [2024-03-16T11:00:18.239] [INFO] GET / [2024-03-16T11:00:18.240] [INFO] GET 405 Get method not working?
> 
> The user part of the config should look like
> 
> ```yaml
> ...
> tgfs:
>   users:
>     test:
>       password: test
> ...
> ```
> 
> in your case, so you can login with username "test" and password "test"
> 
> @Andrew666 FYI

Yes, thanks, it works, but when downloading a file larger than 1mb, everything breaks
![Screenshot_2024-03-16-17-44-43-07_61c78dc80ee02b53007c815fefe993e3](https://github.com/TheodoreKrypton/tgfs/assets/6072553/8b8199bb-5e58-4d5b-8cc3-4f46281b8137)

**Comment by TheodoreKrypton** [comment]
Have you put in a bot token as well? The bot should also be added as an admin of your channel

**Comment by klyamkovya** [comment]
I was able to connect via the WebDAV Total Commander plugin. Everything is fine, the problem can be closed.
I understand correctly, the unlimited storage itself is located in the Telegram channel, and the WebDAV server is only an interface for entering the storage?

**Comment by TheodoreKrypton** [comment]
> I was able to connect via the WebDAV Total Commander plugin. Everything is fine, the problem can be closed. I understand correctly, the unlimited storage itself is located in the Telegram channel, and the WebDAV server is only an interface for entering the storage?

Yes exactly. You can also access the storage via the cmd api. For example:
```bash
tgfs cmd ls /
```
More examples can be found in the README

**Comment by TheodoreKrypton** [comment]
> > Have you put in a bot token as well? The bot should also be added as an admin of your channel
> 
> Yes, the token is correct, the bot has been added to the administrators. Maybe I should also register a bot in this section? manager: host: 0.0.0.0 port: 1901 path: / bot: token: '' chat_id: 0

No the manager is still under development. This section of config shouldn't affect anything. But what is your problem now?

**Comment by Andrew666** [comment]
I use Cyberduck, everything is fine when uploading small files, I get an error message when uploading files larger than 1 MB. I don't know what else to do(

**Comment by klyamkovya** [comment]
I was also happy early (the sprint crashes when uploading a ~3Mb file. Maybe you need to change the value of _chunk_size_kb: 1024_?
![error](https://github.com/TheodoreKrypton/tgfs/assets/59743232/25560301-792b-473b-8a2e-276d36114558)

**Comment by TheodoreKrypton** [comment]
> I was also happy early(. The sprint crashes when uploading a ~3Mb file. Maybe you need to change the value of _chunk_size_kb: 1024_? ![error](https://private-user-images.githubusercontent.com/59743232/313413915-25560301-792b-473b-8a2e-276d36114558.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MTA2NzIsIm5iZiI6MTcxMDYxMDM3MiwicGF0aCI6Ii81OTc0MzIzMi8zMTM0MTM5MTUtMjU1NjAzMDEtNzkyYi00NzNiLThhMmUtMjc2ZDM2MTE0NTU4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDE3MzI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkOTQ1MGNjNTczZTIwN2QwNmI1MjNlNjA2ZmU1NGNkNjVlZmFjODJiZGViYjc0YjliZDYxZGQyYmRmZDI5OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qq9JzhCNTUwAb9j_uQaNvMPISngcytmgDejBd1b6HKM)

No, that field doesn't matter. It is the size for each chunk when downloading files. Can you try the following command to see if it works

```bash
tgfs cmd cp /<path-to-big-file> /remote_file_path
```

**Comment by Andrew666** [comment]
I am running tgfs on a remote linux machine. And I create webdav on my home Windows PC. Unfortunately, I can't spell out the paths

**Comment by klyamkovya** [comment]
I ran the command on ubuntu, where tgfs was running
![error](https://github.com/TheodoreKrypton/tgfs/assets/59743232/f3ed797d-6f8d-4f21-aec9-39ed66fde140)

**Comment by klyamkovya** [comment]
Now the same file via WebDAV
![error](https://github.com/TheodoreKrypton/tgfs/assets/59743232/cd440eee-0a2a-486a-97e7-ff93f3ab7a85)

**Comment by TheodoreKrypton** [comment]
> I ran the command on ubuntu, where tgfs was running ![error](https://private-user-images.githubusercontent.com/59743232/313441784-f3ed797d-6f8d-4f21-aec9-39ed66fde140.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NDcwNjMsIm5iZiI6MTcxMDc0Njc2MywicGF0aCI6Ii81OTc0MzIzMi8zMTM0NDE3ODQtZjNlZDc5N2QtNmY4ZC00ZjIxLWFlYzktMzllZDY2ZmRlMTQwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDA3MjYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwYmRhZjhhZDk3ZGRiNGI4MmFjM2ZhZDE5Y2Y1MDI3NWI1MmU4ODU0ZWI5NWZiY2RlZDVlYTAxOGMwZDJlOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c20hGpJISUIuYcTjPPm1q7TJuagldkx0Es5a9XNebXk)

Can you confirm the file size is between 1MB - 10MB?

**Comment by TheodoreKrypton** [comment]
I tried from my side and it worked without any problem. Can you try to create a new channel and fill the new channel id into config to try again? @klyamkovya  @Andrew666

**Comment by klyamkovya** [comment]
Did. Same problem(

**Comment by TheodoreKrypton** [comment]
> Did. Same problem(. And files uploaded to the channel via Telegram are not visible when connected via WebDAV. Is this how it should be? Could the problem be that ubuntu 192.168.0.110 is on the private network behind the router?

No that should not happen, you should see the file messages when uploading files. Can you see there is a "metadata.json" file created and pinned automatically in the Telegram channel?

**Comment by klyamkovya** [comment]
> No that should not happen, you should see the file messages when uploading files. Can you see there is a "metadata.json" file created and pinned automatically in the Telegram channel?

The file "metadata.json" was created on first launch

**Comment by klyamkovya** [comment]
Я попытался скопировать файл 6 631 496 байт, на канале появилось сообщение 
![tg](https://github.com/TheodoreKrypton/tgfs/assets/59743232/50685a64-a1e6-4a62-8df4-0a98c04d098e)
This is what happened on the console and the script dropped out.
![console](https://github.com/TheodoreKrypton/tgfs/assets/59743232/4a0c4d26-b8e1-4015-bb4d-1fa6aa8c5b2f)
Is there a requirement for the program to run? I have 2Gb RAM on my ubuntu VM

**Comment by TheodoreKrypton** [comment]
> I tried to copy a file of 6,631,496 bytes, a message appeared on the channel 
> 
> ![tg](https://github.com/TheodoreKrypton/tgfs/assets/59743232/50685a64-a1e6-4a62-8df4-0a98c04d098e)
> 
> This is what happened on the console and the script dropped out.
> 
> ![console](https://github.com/TheodoreKrypton/tgfs/assets/59743232/4a0c4d26-b8e1-4015-bb4d-1fa6aa8c5b2f)
> 
> Is there a requirement for the program to run? I have 2Gb RAM on my ubuntu VM

2GB RAM should be enough. Let me add some logging on another branch and please help me test on that branch.

**Comment by klyamkovya** [comment]
> 2GB RAM should be enough. Let me add some logging on another branch and please help me test on that branch.

I'm ready). Where to get the source?

**Comment by TheodoreKrypton** [comment]
@klyamkovya  @Andrew666  Just pushed a new version, please try the latest version. The problem should have been fixed.

**Comment by klyamkovya** [comment]
Thank you. So far this message: "npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

added 698 packages, and audited 699 packages in 5m

63 packages are looking for funding
  run `npm fund` for details"
I will sort this out

**Comment by klyamkovya** [comment]
Thank you. Now files are copied via WebDAV! Should files that are uploaded to a channel from a phone be visible in the list or is such functionality not provided?

**Comment by TheodoreKrypton** [comment]
> Thank you. Now files are copied via WebDAV! Should files that are uploaded to a channel from a phone be visible in the list or is such functionality not provided?

No because you need to go through the tgfs server to update the metainfo.json. The metainfo.json is managing all the directory and files relationship. Maybe in the future I will add a bot to let you upload files through the bot.

**Comment by klyamkovya** [comment]
Clear. Please clarify what file sizes are supported for copying?

**Comment by TheodoreKrypton** [comment]
> Clear. Please clarify what file sizes are supported for copying?

Depends on your account. Premium users can upload single files of up to 2GB I guess. Otherwise 1GB. But I may add a function to partition big files to enable uploading for file of any size.
